column_width = 160
line_endings = "Unix"
indent_type = "Tabs" # Spaces
indent_width = 4
quote_style = "AutoPreferDouble" # AutoPreferSingle
call_parentheses = "Always"

# Specify whether to collapse simple statements.
# Possible options: Never, FunctionOnly, ConditionalOnly, or Always
collapse_simple_statement = "Never"
